name: alan
description: Pure Dart library to easily integrate with any Cosmos-based chain.
version: 0.41.4+1
homepage: https://github.com/alan-sdk/alan.dart
environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  analyzer: ^7.5.0
  asn1lib: ^1.6.5
  bech32: ^0.2.0
  bip39_mnemonic: ^3.0.9
  convert: ^3.1.2
  equatable: ^2.0.7
  fixnum: ^1.1.1
  grpc: ^4.1.0
  hex: ^0.2.0
  http: ^1.4.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  meta: ^1.16.0
  pointycastle: ^4.0.0
  protobuf: ^4.1.0

dev_dependencies:
  build_runner: ^2.5.4
  mockito: ^5.4.6
  mock_web_server: ^5.0.0-nullsafety.1
  test: ^1.26.2
  lints: ^6.0.0
